Add controllers
LLaym/java-shareit pull request #1
Opened 2023-06-09 16:58 UTC by LLaym

Привет!
Кратко по изменениям из ТЗ №12: Реализованы эндпоинты по работе с сущностями User и Item
Хотелось бы увидеть замечания к работе (боюсь за валидацию).
Спасибо!)

2023-06-10 08:43 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-06-10 08:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +    UserDto addNewUser(UserDto userDto);
Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `filmService.createFilm()`

Получается масло-масляное! 

Лучше: `filmService.create()` `userService.update()`

2023-06-10 08:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/exception/EmailAlreadyExistException.java
> +public class EmailAlreadyExistException extends RuntimeException {
Не нужно создавать настолько специфичные исключения.
Нужен один общий `AlreadyExistException` то что это email ты отразишь в сообщении.

2023-06-10 08:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/dao/UserDao.java
> +    User findById(long id);
Тут очень удобно, при выборке одиночного объекта, возвращать `Optional`

`Optional<User> findById(long id);`

2023-06-10 08:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDao.java
> +        for (Item item : items.values()) {
Зачем же мы Map, у которого доступ к элементу за `O(1)` развернули в List, у которого поиск за `O(n)`. Стало алгоритмически сильно хуже! Перемудрил же!

Может так?
```
return items.get(id) != null;
```

2023-06-10 08:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        checkUserExist(userId);
Ты называешь метод check - проверка. Но паттерн проверки подразумевает что мы дадим какой-то ответ по результатам проверки... а мы кидаемся исключением.
Это не неожиданно от такого метода.
Давай дадим ему более говорящее название `throwIfUserNotExist`

2023-06-10 08:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        checkItemExist(id);
Item я рекомендую не чекать отдельно, раз он нужен тебе вот буквально сразу.
Перепиши метод findById, чтобы он возвращал Optional и воспользуйся методом  orElseThrow

2023-06-10 08:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Item> items = itemDao.findAllBySubstring(substring).stream()
Тут нужно по полной воспользоваться функциональщиной, приведу пример

```
    public List<ItemDto> getAllItemsBySubstring(long userId, String substring) {
        checkUserExist(userId);

        List<ItemDto> itemsDtos = itemDao.findAllBySubstring(substring).stream()
                                         .filter(Item::getAvailable)
                                         .map(itemMapper::toItemDto)
                                         .collect(Collectors.toList());

        log.info("Передан список найденных вещей по запросу {}: {}", substring, itemsDtos);

        return itemsDtos;
    }
```

2023-06-10 08:43 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Item> items = itemDao.findAllBySubstring(substring).stream()
А если убрать лог

```
    public List<ItemDto> getAllItemsBySubstring(long userId, String substring) {
        checkUserExist(userId);

        return itemDao.findAllBySubstring(substring).stream()
                      .filter(Item::getAvailable)
                      .map(itemMapper::toItemDto)
                      .collect(Collectors.toList());
    }
```

2023-06-10 18:55 UTC, FanaticFiz approved these changes

2023-06-10 18:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDao.java
> +            return Collections.emptyList();
У List тоже такая штука есть -> `List.of()`

2023-06-10 18:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDao.java
> +        } else {
Можно избавится от else и лишних () в условии

```
    public List<Item> findAllBySubstring(String substring) {
        String query = substring.toLowerCase();
        if (query.equals("")) {
            return List.of();
        }

        return items.values().stream()
                    .filter(item -> item.getName().toLowerCase().contains(query)
                            || item.getDescription().toLowerCase().contains(query))
                    .collect(Collectors.toList());
    }
```

2023-06-10 18:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        userDao.findById(userId)
Пришлось 5-ть раз написать одно и тоже!
Отличный повод вынести в небольшой метод

```
    private void throwIfUserNotExist(long userId) {
        userDao.findById(userId)
               .orElseThrow(() -> new NotFoundException("Пользователь с id " + userId + " не найден"));
    }
```

2023-06-10 18:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemMapper.toItemDto(item);
И вот еще пример, вот так мог бы выглядеть метод в целом, теперь когда у нас Optional

```
    @Override
    public ItemDto getById(long userId, long id) {
        throwIfUserNotExist(userId);

        return itemDao.findById(id)
                      .map(itemMapper::toItemDto)
                      .orElseThrow(() -> new NotFoundException("Вещь с id " + id + " не найдена"));
    }
```

2023-06-10 18:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            throw new AlreadyExistException("Такой email уже существует");
"Такой" - это какой?
Помоги сам себе дополни лог или иное сообщение подробностями!

2023-06-11 09:22 UTC, LLaym commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemMapper.toItemDto(item);
Но тогда придётся убрать логирование в этом методе..

2023-06-11 09:28 UTC, merged