Add bookings
LLaym/java-shareit pull request #2
Opened 2023-06-26 09:05 UTC by LLaym

Привет!)
PR по ТЗ №14. Реализован функционал аренды (booking)
Спасибо!

2023-06-26 18:55 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-06-26 18:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ValidationException("End date not in future");
Проверка входных параметров на адекватность это обязанность контроллера

2023-06-26 18:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        booking.setStatus(BookingStatus.WAITING);
Можно предварительно заимпортить статики, в основном коде получим удобство и читаемость
`booking.setStatus(WAITING);`

2023-06-26 18:55 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS bookings (
Было бы неплохо причесать

```
CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name         VARCHAR(256) NOT NULL,
    description  VARCHAR(512) NOT NULL,
    is_available BOOLEAN      NOT NULL,
    request_id   BIGINT       REFERENCES requests (id) ON DELETE SET NULL
);
```

2023-06-26 18:55 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    .filter(booking -> booking.getStatus() != BookingStatus.REJECTED)
Такое ощущение что ты злоупотребляешь фильтрами.
Т.е. сначала делаешь выборку из базы, получаешь не то что нужно и начинаешь кодом фильтровать. 

Напиши такой запрос чтобы не пришлось делать дополнительную фильтрацию кодом. 
Используй NativeQuery если собирать по параметрам длинно очень.

2023-06-27 08:57 UTC, LLaym commented
Поймал кошку в течение 2х минут!
![изображение](https://github.com/LLaym/java-shareit/assets/113213520/8b8f16f4-8d27-4d3b-beba-9607ae63fced)

2023-06-27 18:50 UTC, FanaticFiz approved these changes

2023-06-28 06:46 UTC, merged